apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: my-custom-moodle:latest
        ports:
        - containerPort: 80
        env:
        - name: MOODLE_DATABASE_HOST
          value: "moodle-mariadb"
        - name: MOODLE_DATABASE_USER
          value: "bn_moodle"
        - name: MOODLE_DATABASE_PASSWORD
          value: "password"
        - name: MOODLE_DATABASE_NAME
          value: "bitnami_moodle"
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: moodle
